version: '3'

services:
  database:
    image: 'postgres:13.1-alpine'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    image: 'codecoin:latest'
    ports:
      - '8081:8080'
    build:
      context: .
    container_name: codecoin
    depends_on:
      - database
    environment:
      - PSQL_HOST=database
      - PSQL_DB_NAME=postgres
      - PSQL_USERNAME=postgres
      - PSQL_PASSWORD=postgres
      - SECRET_KEY=secret
