name: Deploy to Heroku
on:
  workflow_run:
    workflows: [Maven build Java]
    types:
      - completed

jobs:
  on-success:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - name: set permissions
        - run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE
        - name: checkout repo
          uses: actions/checkout@v2
        - name: Build, Push and Deploy to Heroku
          id: heroku
          uses: jctaveras/heroku-deploy@v2.1.3
          with:
            email: ${{ secrets.HEROKU_EMAIL }}
            api_key: ${{ secrets.HEROKU_API_KEY }}
            app_name: ${{ secrets.HEROKU_APP_NAME }}
            dockerfile_path: ''
